let userScore = 0;
let computerScore = 0;
const userScore_span = $("#user-score");
const computerScore_span = $("#computer-score");
const scoreBoard_div = $(".score-board");
const result_p = $(".result > p");
const rock_div = $("#r");
const paper_div = $("#p");
const scissors_div = $("#s");

// getting the random number generated by the computer
function getcomputerChoice() {
    const choices = ['r' ,'p', 's'];
    const randomNumber = Math.floor(Math.random()*3);

  return choices[randomNumber];
    
}

function convertText(text) {
    switch (text) {
        case "r":
            return "Rock"
            break;

            case "p":
            return "Paper"
            break;

            case "s":
            return "Scissors"
            break;
    
        default:
            break;
    }
}

function win(userChoice,computerChoice){
    userScore++;
    userScore_span.html(userScore);
    result_p.html(convertText(userChoice) + " beats " + convertText(computerChoice) + ". You Win 🔥");
    $("#" + userChoice).addClass("green-glow");
    setTimeout(function () {
        $("#" + userChoice).removeClass("green-glow");
    },300)
}
function lose(userChoice,computerChoice){
    computerScore++;
    computerScore_span.html(computerScore);
    result_p.html(convertText(userChoice) + " loses to " + convertText(computerChoice) + ". You Lose 😒");
    $("#" + userChoice).addClass("red-glow");
    setTimeout(function () {
        $("#" + userChoice).removeClass("red-glow");
    },300)

}

function draw(userChoice,computerChoice){
    result_p.html(convertText(userChoice) + " equals " + convertText(computerChoice) + ". It's Draw");
    $("#" + userChoice).addClass("gray-glow");
    setTimeout(function () {
        $("#" + userChoice).removeClass("gray-glow");
    },300)
}

function game(userChoice){
    const computerChoice = getcomputerChoice();
    switch (userChoice + computerChoice) {
        case "rs":
        case "pr":
        case "sp":
            win(userChoice, computerChoice);

            break;
        case "rp":
        case "ps":
        case "sr":
            lose(userChoice, computerChoice);

            break;
        case "rr":
        case "pp":
        case "ss":
            draw(userChoice, computerChoice);
        default:
            break;
    }

}


function main() {

        // rock onclick fn
    rock_div.click(function(){

        game("r");

    });
    // paper onclick fn
    paper_div.click(function(){

        game("p")

    });
    // Scissors onclick fn
    scissors_div.click(function(){

        game("s")

    }); 
    
}

main();
